# Create a acme.json file on the host:
# $ touch acme.json && chmod 600 acme.json

version: '3.3'

networks:
  web:
    external: true

services:

  traefik:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json # SET THE RIGHT PATH
      - ./traefik.toml:/traefik.toml # SET THE RIGHT PATH
    networks:
      - web
    labels:
      - "traefik.enable=false"
