postgis:
    build: ./postgis
    ports:
        - 5432:5432
    environment:
        - GC2_PASSWORD=xxxxxx
elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - ./elasticsearch/data:/usr/share/elasticsearch/data
geoserver:
    build: ./geoserver
    ports:
        - "8080:8080"
    links:
        - postgis:postgis
kibana:
    build: kibana/
    volumes:
        - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
        - "5601:5601"
    links:
        - elasticsearch
    environment:
        - NODE_OPTIONS=--max-old-space-size=200
gc2core:
    build: ./gc2core
    ports:
        - "80:80"
        - "443:443"
        - "1339:1339"
    links:
        - postgis:postgis
        - elasticsearch:elasticsearch
        - geoserver:geoserver
    # volumes:
    #     - ~/apache2/ssl:/etc/apache2/ssl
    #     - ~/apache2/sites-enabled:/etc/apache2/sites-enabled/
    #     - ~/fpm:/etc/php5/fpm/
    #     - ~/gc2/conf:/var/www/geocloud2/app/conf
    #     - ~/gc2/tmp:/var/www/geocloud2/app/tmp
    #     - ~/gc2/mapcache:/var/www/geocloud2/app/wms/mapcache
    environment:
        - GC2_PASSWORD=xxxxxx
mapcache:
    build: ./mapcache
    net: container:gc2core
    volumes:
        - ~/gc2/mapcache:/var/www/geocloud2/app/wms/mapcache
        - ~/gc2/tmp:/var/www/geocloud2/app/tmp
