# Create a acme.json file on the host:
# $ touch acme.json && chmod 600 acme.json

version: '3.3'

networks:
  web:
    external: true

configs:
  traefik.toml:
    file: ./traefik.toml

services:

  traefik:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/acme.json:/acme.json # SET THE RIGHT PATH
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
    labels:
      - "traefik.enable=false"
    networks:
      - web

    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]