#
# This Docker-compose file is for traefik in a Docker standalone environment
#
# How to:
#
# Create a user defined overlay network:
# $ docker network create --driver overlay web
#
# The run following command to deploy:
#
# $ docker stack deploy --compose-file docker-compose.yml traefik
#
# Remember to set email!

version: '3.3'

networks:
  web:
    external: true

services:
  traefik:
    image: traefik
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=mh@mapcentia.com" # SET EMAIL
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=traefik"
      - "--docker.watch"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    networks:
      - web
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]